title: Arian Å ajina
description: An experiment in personal digital space.
author: ariansajina.write@proton.me

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty

header_pages:
  - about.md
  - calendar.md
show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
