title: Arian Sajina
description: Personal blog.
author: Arian Sajina

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty
show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
