title: Arian Sajina
description: Personal blog.
author: Arian Sajina

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty

header_pages:
  - about.md
  - calendar.md
show_excerpts: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
